---
abstract: 'Encapsulated, declarative class style'
author:
  - 'Aristotle Pagaltzis <pagaltzis@gmx.de>'
  - 'Luke Palmer'
build_requires:
  Baz: 0
  File::Find: 0
  File::Temp: 0
  Foo: 0
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.029, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Class-Closure
requires:
  Carp: 0
  Devel::Caller: 0
  Exporter: 0
  PadWalker: 0
  Sentinel: 0
  Symbol: 0
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  bugtracker: http://github.com/ap/Class-Closure/issues
  homepage: http://github.com/ap/Class-Closure
  repository: git://github.com/ap/Class-Closure
version: 0.301
