---
abstract: 'Encapsulated, declarative class style'
author:
  - 'Aristotle Pagaltzis <pagaltzis@gmx.de>'
  - 'Luke Palmer'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.101550, CPAN::Meta::Converter version 2.101461'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Class-Closure
requires:
  Devel::Caller: 0
  PadWalker: 0
resources:
  bugtracker: http://github.com/ap/Class-Closure/issues
  homepage: http://github.com/ap/Class-Closure
  repository: git://github.com/ap/Class-Closure
version: 0.30
